// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: exmaples/grpc/basic/protos/chat.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UnixMilli     int64                  `protobuf:"varint,4,opt,name=unix_milli,json=unixMilli,proto3" json:"unix_milli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_exmaples_grpc_basic_protos_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_exmaples_grpc_basic_protos_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_exmaples_grpc_basic_protos_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetUnixMilli() int64 {
	if x != nil {
		return x.UnixMilli
	}
	return 0
}

var File_exmaples_grpc_basic_protos_chat_proto protoreflect.FileDescriptor

const file_exmaples_grpc_basic_protos_chat_proto_rawDesc = "" +
	"\n" +
	"%exmaples/grpc/basic/protos/chat.proto\x12\x04chat\"n\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"unix_milli\x18\x04 \x01(\x03R\tunixMilli2?\n" +
	"\vChatService\x120\n" +
	"\x04Chat\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x010\x01BCZAgithub.com/lk2023060901/zeus-go/exmaples/grpc/basic/protos;protosb\x06proto3"

var (
	file_exmaples_grpc_basic_protos_chat_proto_rawDescOnce sync.Once
	file_exmaples_grpc_basic_protos_chat_proto_rawDescData []byte
)

func file_exmaples_grpc_basic_protos_chat_proto_rawDescGZIP() []byte {
	file_exmaples_grpc_basic_protos_chat_proto_rawDescOnce.Do(func() {
		file_exmaples_grpc_basic_protos_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exmaples_grpc_basic_protos_chat_proto_rawDesc), len(file_exmaples_grpc_basic_protos_chat_proto_rawDesc)))
	})
	return file_exmaples_grpc_basic_protos_chat_proto_rawDescData
}

var file_exmaples_grpc_basic_protos_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exmaples_grpc_basic_protos_chat_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: chat.ChatMessage
}
var file_exmaples_grpc_basic_protos_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.Chat:input_type -> chat.ChatMessage
	0, // 1: chat.ChatService.Chat:output_type -> chat.ChatMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exmaples_grpc_basic_protos_chat_proto_init() }
func file_exmaples_grpc_basic_protos_chat_proto_init() {
	if File_exmaples_grpc_basic_protos_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exmaples_grpc_basic_protos_chat_proto_rawDesc), len(file_exmaples_grpc_basic_protos_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exmaples_grpc_basic_protos_chat_proto_goTypes,
		DependencyIndexes: file_exmaples_grpc_basic_protos_chat_proto_depIdxs,
		MessageInfos:      file_exmaples_grpc_basic_protos_chat_proto_msgTypes,
	}.Build()
	File_exmaples_grpc_basic_protos_chat_proto = out.File
	file_exmaples_grpc_basic_protos_chat_proto_goTypes = nil
	file_exmaples_grpc_basic_protos_chat_proto_depIdxs = nil
}
